# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0003_auto_20160611_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon',
            name='username',
            field=models.TextField(max_length=50),
        ),
    ]
