# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartoon', '0005_auto_20160611_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='ct_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoon_id', to='cartoon.Cartoon'),
        ),
    ]
